apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"dracula","namespace":"production"}}
  creationTimestamp: "2019-11-14T19:02:41Z"
  name: dracula-old
  namespace: production
  resourceVersion: "80853806"
  uid: 55645726-0711-11ea-8043-02a14e2b240e
secrets:
- name: dracula-token-8cswc
