apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::id:role/k3-dracula
  name: dracula
  namespace: production
secrets:
  - name: dracula-token-8cswc
#  Error: UPGRADE FAILED: rendered manifests contain a resource that already exists.
#Unable to continue with update: ServiceAccount "dracula" in namespace "production" exists and
#cannot be imported into the current release: invalid ownership metadata; label validation error:
#missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key
#"meta.helm.sh/release-name": must be set to "dracula-helm"; annotation validation error:
#missing key "meta.helm.sh/release-namespace": must be set to "production"
