// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use uuid::Uuid;

#[derive(Queryable, Debug)]
pub struct Inventory {
    pub id: i64,
    pub inventory_group_id: Option<i32>,
    pub data: Option<serde_json::Value>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub uuid: Option<Uuid>,
    pub product_name: Option<String>,
    pub product_url: Option<String>,
    pub provider_id: Option<i32>,
}
