name: Release docker image

on:
  push:
#    branches:
#      - 'main'
    tags:
      - '*'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  REPO: dracula

jobs:
  build:
    runs-on: ["amd64"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::id:role/gha-dracula
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run sccache-cache
        uses: mozilla/sccache-action@eaed7fb9f8fb32adea8bd40d7f276f312de9beaf
        with:
          version: "v0.4.0-pre.10"

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Check brotli
        run: ldconfig -p | grep brotli

      - name: Build
        run: docker build -t ${{ fromJSON(steps.meta.outputs.json).tags[0] }} .

      - name: Push
        run: docker push ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
